version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - web

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        SERVICE_TYPE: web
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - queue
    environment:
      - REDIS_HOST=redis

  queue:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        SERVICE_TYPE: queue
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
      - '5540:5540'
